// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaqjpsfllarjljywlrjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhcWpwc2ZsbGFyamxqeXdscmpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5OTQ5MzMsImV4cCI6MjA2NzU3MDkzM30.RiVR6-WzeDL09kMC4_V-4Don5lA0VB9eQV3zfyJK-o8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});